
name: My Angular Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Build and run Angular app
      run: |
        npm install
        ng build --prod
        node dist/my-app/main.js
    env:
      NODE_ENV: production
