name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start server
        run: |
          nohup npm start >server.log &
          sleep 30s
      - name: Autograde
        uses: education/autograding@v1